declare module '@mui/material/styles' {
  interface Palette {
    purple: Palette['primary']
    brown: Palette['primary']
    orange: Palette['primary']
    yellow: Palette['primary']
    green: Palette['primary']
    lightGrey: Palette['primary']
    lightYellow: Palette['primary']
    lightBrown: Palette['primary']
    lightWhite: Palette['primary']
    mediumGrey: Palette['primary']
    midGrey: Palette['primary']
    lowOpacityGrey: Palette['primary']
    lowOpacityPurple: Palette['primary']
    lowOpacityGrey: Palette['primary']
    lowOpacityYellow: Palette['primary']
    lowOpacityWhite: Palette['primary']
    blue: Palette['primary']
    emerald: Palette['primary']
    lightGreen: Palette['primary']
    darkGreen: Palette['primary']
    yellow: Palette['primary']
    brown: Palette['primary']
    lightOrange: Palette['primary']
    warmBrown: Palette['primary']
  }
  interface PaletteOptions {
    purple?: PaletteOptions['primary']
    orange?: PaletteOptions['primary']
    brown?: PaletteOptions['primary']
    yellow?: PaletteOptions['primary']
    green?: PaletteOptions['primary']
    lightGrey?: PaletteOptions['primary']
    lightYellow?: PaletteOptions['primary']
    lightBrown?: PaletteOptions['primary']
    lightWhite?: PaletteOptions['primary']
    mediumGrey?: PaletteOptions['primary']
    midGrey?: PaletteOptions['primary']
    lowOpacityGrey?: PaletteOptions['primary']
    lowOpacityPurple?: PaletteOptions['primary']
    lowOpacityGrey?: PaletteOptions['primary']
    lowOpacityYellow?: PaletteOptions['primary']
    lowOpacityWhite?: PaletteOptions['primary']
    blue?: PaletteOptions['primary']
    emerald?: PaletteOptions['primary']
    lightGreen?: PaletteOptions['primary']
    darkGreen?: PaletteOptions['primary']
    yellow?: PaletteOptions['primary']
    brown?: PaletteOptions['primary']
    lightOrange?: PaletteOptions['primary']
    warmBrown?: PaletteOptions['primary']
  }
}

export {}
